---
title: "traits_review_newmodels"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Workspace Load}

library(knitr)
library(tidyverse)
library(vegan)
library(ggplot2)
library(viridis)
library(plyr)

library(dplyr)
library(PNWColors)
library(mvabund)
library(reshape2)
library(gridExtra)
library(ggbiplot)
library(openxlsx)
library(cowplot)
library(forcats)
library(goeveg)

```

## Secondary trait classification

### Load and manipulate the data

```{r Secondary Data Load, include=F, eval=F, echo=T}
#This contains a cleaned up dataset of several hundred traits that have been "summarised" by a process they model, rather than completely disaggregated unique traits for which we had over 2000
#Load data
review_traits_2nd <- read_csv("secondary_traits_fill_dummy.csv")
#Check dataframe
glimpse(review_traits_2nd)

#summary(as.factor(review_traits_2nd$TOS))
#Note that there are 4 NA's under type of study and we may need to omit these.
#summary(as.factor(review_traits_2nd$`Taxonomic`))
#        Birds         Fish Herpetofauna      Insects      Mammals     Multiple        Other 
#         155          324           91          339          105          393          230 
#    Plankton       Plants 
#          66          614 

#Need to rename Predictive values
#Need to rename and create some key variables for grouping factors
```

```{r Secondary Data Manipulation, include=F, eval=F, echo=T}

#Also found a typo, there are probably loads more
review_traits_2use = review_traits_2nd %>%
  group_by(DOI) %>%
  sample_n(1) %>%
  dplyr::rename(Predictive = `Forecasting`) %>%
  mutate(`GlobalChangeCat`=if_else(`GlobalChange`>0, "yes", "no"), #Add binary column for presence/absence of Global Change Driver 
         `Taxonomic Group`=case_when( #Note can use case_when() or if_ele() BUT you need to write one for each value and not try to combine them as strings using c()
           `Taxonomic` == "Mammals" ~ "Vertebrate",
           `Taxonomic` == "Birds" ~ "Vertebrate",
           `Taxonomic` == "Fish" ~ "Vertebrate",
           `Taxonomic` == "Herpetofauna" ~ "Vertebrate",
           `Taxonomic` == "Plankton" ~ "Invertebrate",
           `Taxonomic` == "Insects" ~ "Invertebrate",
           `Taxonomic` == "Multiple" ~ "Multiple",
           `Taxonomic` == "Other" ~ "Other",
           `Taxonomic` == "Plants" ~ "Plants")
         ) %>%
  select(`DOI`:`Taxonomic`,`Taxonomic Group`,`GlobalChange`,`GlobalChangeCat`,  `Predictive`:`zinc`) %>%
  #Can remove: web-building and diving ability are problematic NMDS1 axis #, -c(`web making`, `diving ability`)
  #Need to leave this in
  filter(TOS != "NA")

#####Need to remove any columns and rows that sum to 1

glimpse(review_traits_2use)
dim(review_traits_2use) #821 observations and 230 columns


#These data do not contain zero sum columns or rows
#CREATE SUBSETS FOR ANALYSES
review_sites_2nd <- review_traits_2use[,1:10]
#review_species_2nd <- review_traits_2use[,11:ncol(review_traits_2use)] #220 trait columns
#Check for zero sum rows and columns
#which(colSums(review_traits_2use[,11:ncol(review_traits_2use)])==1) #none are zero but several are 1's


```

```{r Secondary Data Simplification}

# Remove columns and rows that sum to 1 from the dataframe

#Remove columns that only contain a single occurrence for a trait, as well as any zero sum rows
review_traits_2 = review_traits_2use[,-which(colSums(review_traits_2use[,11:ncol(review_traits_2use)])<2)]
str(review_traits_2)
review_traits_2 = review_traits_2[,9:ncol(review_traits_2)]
str(review_traits_2) #Classes ‘tbl_df’, ‘tbl’ and 'data.frame'

#NOTE
#We go from having 220 traits observed to 182 observed more than once.

#Not sure why some explanatory variable columns disappear also, so adding them back in:
dim(review_traits_2) #821 rows of observations and 182 columns
length(review_traits_2) #182
dim(review_sites_2nd)
length(review_sites_2nd) #10

str(review_sites_2nd) #Classes ‘grouped_df’, ‘tbl_df’, ‘tbl’ and 'data.frame':

#This did not work! I do not know why...
#review_traits_2.0 = as.data.frame(cbind(review_sites_2nd, review_traits_2)) #Error: number of rows of result is not a multiple of vector length (arg 1)

review_traits_2.0 = data.frame(review_sites_2nd, review_traits_2, stringsAsFactors=TRUE)
dim(review_traits_2.0)
str(review_traits_2.0)

#Then delete rows that sum to zero for the trait occurrences
review_traits_2simpler = review_traits_2.0[-which(rowSums(review_traits_2.0[,11:ncol(review_traits_2.0)])==0),] #1099 observations of 1415 traits

#str(review_traits_2use)
#View(review_traits_2[,9:ncol(review_traits_2)])

#USE THESE SUBSETS
review_sites_2nd <- review_traits_2simpler[,1:10] #10 co-variates
review_species_2nd <- review_traits_2simpler[,11:ncol(review_traits_2simpler)] #182 trait columns 787 observations

View(review_species_2nd)
```


### Ordination

```{r Ordination 2nd}
#Secondary classification for traits
#Ordination based on single replicate for each study
traits_ord_2nd <- metaMDS(review_species_2nd,
                          distance = "jaccard",
                          trymax = 99, #increase to 1000
                          k = 3) #increase trymax = 50

#View(traits_ord_2nd$species)


#try removing the NA's
#need to identify and remove the outliers
#looks like web-building and diving ability are problematic NMDS1 axis

#None of my graphics code is working today

saveRDS(traits_ord_2nd, "traits_ord_2nd.rds")

#traits_ord_2nd <- readRDS("traits_ord_2nd.rds")

#Plot NMDS --> 

plot(traits_ord_2nd) #plots species (here traits) as black dots, sites (here studies) as red crosses, not labelled


```


```{r ORD visualise 2nd}

#None of the plotting techniques are working
plot(traits_ord_2nd, type = "n") #plots species as black dots, traits as red crosses, not labelled
points(traits_ord_2nd, pch = 16, cex = 2.5) #, col = vert.pal[NMDS_data2$vert_habitat],
ordihull(traits_ord_2nd, NMDS_data2$vert_habitat, draw = "polygon", col = vert.pal)
legend("bottomright", legend=levels(NMDS_data2$vert_habitat), col=vert.pal, pch = 16, cex = 1.75)

data(dune)

plot(traits_ord_2nd, display = "sites", type = "n")
with(review_sites_2nd, points(traits_ord_2nd, disp = "si", pch = as.numeric(review_sites_2nd$Predictive)))
with(dune.env, legend("topleft", levels(Management), pch = 1:4,
title = "Management"))
with(dune.env, ordiellipse(mod, Management, label = TRUE))
## add
```



### Ordination

```{r Ordination 1ry}

#Primary classification for traits
#Ordination based on single replicate for each study
traits_ord_1ry <- metaMDS(review_species_1ry,
                          distance = "jaccard",
                          trymax = 50, #rerun and increase to 1000
                          k = 3) #increase trymax = 50

traits_ord_1ry[["stress"]] #stress = 0.07954742 #very low could be underdispersed

plot(traits_ord_1ry) #plots species (here traits) as black dots, sites (here studies) as red crosses, not labelled

saveRDS(traits_ord_1ry, "traits_ord_1ry.rds")

```

```{r LOAD ORDINATION}

#Reload ordination
#traits_ord_1ry = readRDS("traits_ord_1ry.rds")

```

```{r ORD Visualisation}

#Don't run

#str(traits_ord_1ry)

#Plot base plot
ordiplot(traits_ord_1ry, type = "none") #creates blank plot
orditorp(traits_ord_1ry, display = "species", col = "red", air=0.01) #labels traits
#where the species were plotted as their species id#
orditorp(traits_ord_1ry, display = "sites", cex = 0.7, air=0.01) #labels species 


```


```{r Data scores for plotting - USE}

#Extract NMDS coordinates and associate with co-variates/grouping factors

data.scores <- as.data.frame(scores(traits_ord_1ry))  
#Using the scores function from vegan to extract the site scores and convert to a data.frame
data.scores$points <- rownames(data.scores)  
# create a column of site names, from the rownames of data.scores
treatment.scores <- cbind(review_sites_1ry, data.scores)

#bind treatment labels and score values

#Check
str(treatment.scores)  

```

#Convex hull calculations
For each ordination and set of grouping variables input to data scores chunk

```{r Convex hulls - Ecosystem}
# Ecosystem type
View(treatment.scores)
#Create convex hulls for the space occupied by each Ecosystem type
unique(treatment.scores$Ecosystem) #"Terrestrial" "Freshwater"  "Marine"      "Broad"
treatment.scores$Ecosystem <- as.factor(treatment.scores$Ecosystem)
summary(treatment.scores$Ecosystem)

#Terrestrial
grp.t <- treatment.scores[treatment.scores$Ecosystem == "Terrestrial", ][chull(treatment.scores[treatment.scores$Ecosystem == "Terrestrial", c("NMDS1", "NMDS2")]), ] 
#Freshwater
grp.f <- treatment.scores[treatment.scores$Ecosystem == "Freshwater", ][chull(treatment.scores[treatment.scores$Ecosystem == "Freshwater", c("NMDS1", "NMDS2")]), ] 
#Marine
grp.m <- treatment.scores[treatment.scores$Ecosystem == "Marine", ][chull(treatment.scores[treatment.scores$Ecosystem == "Marine", c("NMDS1", "NMDS2")]), ]
#Broad
grp.b <- treatment.scores[treatment.scores$Ecosystem == "Broad", ][chull(treatment.scores[treatment.scores$Ecosystem == "Broad", c("NMDS1", "NMDS2")]), ]
#combine the hull data
hull.data.ecos <- rbind(grp.t, grp.f, grp.m, grp.b)  
hull.data.ecos
```

```{r Convex hulls - Global Change}
#Global Change yes/no
#Create convex hulls for the space occupied by each Ecosystem type
unique(treatment.scores$`Global Change`) #no/yes
treatment.scores$`Global Change` <- as.factor(treatment.scores$`Global Change`)
summary(treatment.scores$`Global Change`)

#Yes
grp.climyes <- treatment.scores[treatment.scores$`Global Change` == "yes", ][chull(treatment.scores[treatment.scores$`Global Change` == "yes", c("NMDS1", "NMDS2")]), ] 
#No
grp.climno <- treatment.scores[treatment.scores$`Global Change` == "no", ][chull(treatment.scores[treatment.scores$`Global Change` == "no", c("NMDS1", "NMDS2")]), ] 

#combine the hull data
hull.data.clim <- rbind(grp.climyes, grp.climno)  
hull.data.clim
```

```{r Convex hulls - Taxonomic specific}
# Taxonomic groups
#Create convex hulls for the space occupied by each Taxonomic values
unique(treatment.scores$Taxonomic) 
treatment.scores$Taxonomic <- as.factor(treatment.scores$Taxonomic)
#Change some of the values
levels(treatment.scores$Taxonomic)[levels(treatment.scores$Taxonomic)=="Broad"] <- "Multiple"
levels(treatment.scores$Taxonomic)[levels(treatment.scores$Taxonomic)=="Herps"] <- "Reptiles"
#"Birds"    "Insects"  "Mammals"  "Broad"    "Multiple" "Other"    "Fish"     "Herps"    "Plants"   "Plankton"
summary(treatment.scores$Taxonomic)

#Example loop
#for (unique(treatment.scores$Taxonomic) in treatment.scores$Taxonomic){
#  print(paste("Taxon is", unique(treatment.scores$Taxonomic)))
#}
View(treatment.scores$Taxonomic)

#Taxonomic group - hull loop
tax = as.character(unique(treatment.scores$Taxonomic))
for(i in 1:length(tax)) {
  temp = tax[i]
  df = treatment.scores[treatment.scores$Taxonomic == temp, ][chull(treatment.scores[treatment.scores$Taxonomic == temp, c("NMDS1", "NMDS2")]), ]
  assign(paste0('grp.',temp), df)
}

#combine the hull data
hull.data.taxon <- rbind(grp.Birds, grp.Insects, grp.Mammals, grp.Multiple, grp.Other, grp.Fish, grp.Reptiles, grp.Plants, grp.Plankton)  
head(hull.data.taxon)
```

```{r Convex hulls - Taxonomic Group}
# Taxonomic groups
#Create convex hulls for the space occupied by each Taxonomic values
unique(treatment.scores$`Taxonomic Group`) 

#Taxonomic group - hull loop
taxgrp = as.character(unique(treatment.scores$`Taxonomic Group`))
for(i in 1:length(taxgrp)) {
  temp = taxgrp[i]
  df = treatment.scores[treatment.scores$`Taxonomic Group` == temp, ][chull(treatment.scores[treatment.scores$`Taxonomic Group` == temp, c("NMDS1", "NMDS2")]), ]
  assign(paste0('grp.',temp), df)
}

#combine the hull data
hull.data.taxgrp <- rbind(grp.Vertebrate, grp.Invertebrate, grp.Multiple, grp.Other, grp.Plants)  
head(hull.data.taxgrp)
```

```{r Convex hulls - Type of Study}
# Type of study
unique(treatment.scores$TOS)
#TModel --> Theory
treatment.scores$TOS <- as.factor(treatment.scores$TOS)
levels(treatment.scores$TOS)[levels(treatment.scores$TOS)=="TModel"] <- "Theory"
#Create convex hulls for the space occupied by each Type of study
#Hull loop
tos = as.character(unique(treatment.scores$TOS))
for(i in 1:length(tos)) {
  temp = tos[i]
  df = treatment.scores[treatment.scores$TOS == temp, ][chull(treatment.scores[treatment.scores$TOS == temp, c("NMDS1", "NMDS2")]), ]
  assign(paste0('grp.',temp), df)
}

#combine the hull data
hull.data.tos <- rbind(grp.Observational, grp.Experiment, grp.Metanalysis, grp.Theory, grp.Review)  
```

```{r Convex hulls - Filter}
# Level of filtering

#Make following value changes
#"Fundamental" --> Abiotic
#"Physical" --> Dispersal 
#"Ecological"  --> Biotic
#"Trophic" = "Trophic"
treatment.scores$Filter <- as.factor(treatment.scores$Filter)
levels(treatment.scores$Filter)[levels(treatment.scores$Filter)=="Fundamental"] <- "Abiotic"
levels(treatment.scores$Filter)[levels(treatment.scores$Filter)=="Physical"] <- "Dispersal"
levels(treatment.scores$Filter)[levels(treatment.scores$Filter)=="Ecological"] <- "Biotic"

#Create convex hulls for the space occupied by each Type of study
#Hull loop
filt = as.character(unique(treatment.scores$Filter))
for(i in 1:length(filt)) {
  temp = filt[i]
  df = treatment.scores[treatment.scores$Filter == temp, ][chull(treatment.scores[treatment.scores$Filter == temp, c("NMDS1", "NMDS2")]), ]
  assign(paste0('grp.',temp), df)
}


#combine the hull data
hull.data.filt <- rbind(grp.Abiotic, grp.Biotic, grp.Trophic, grp.Dispersal)  
unique(hull.data.filt$Filter)
summary(treatment.scores$Filter)

```

